### ISSUE TITLE
Code structure for Python (at least) is not correct

### ISSUE THREAD

**Issue by soke1556** [Codealike/Codealike-Jetbrains#30]
Apparently, the saved structure for Python projects (PyCharm) doesn't represent the proper data structure needed by Codealike. Thus, the reports doesn't show the data at file level (which is the only one possible).

The ActivityEntryCollection doesn't host any Event.

{
    "Instance": "738369593",
    "MachineName": "CV-009",
    "Owner": "membership/account/soke",
    "Extension": "0.0.1",
    "Client": "PyCharmCore",
    "Solution": "SolutionContexts/1",
    "States": [
        {
            "Events": [],
            "Id": "activitystateentries/5",
            "StartTicks": 636244084912520000,
            "EndTicks": 636244084960300000,
            "DurationTicks": 47780000,
            "Type": "Idle"
        },
        {
            "Events": [],
            "Id": "activitystateentries/6",
            "StartTicks": 636244084960300000,
            "EndTicks": 636244085112370000,
            "DurationTicks": 152070000,
            "Type": "Idle"
        }
    ],
    "StartTimeTicks": 636244084912520000,
    "EndTimeTicks": 636244085112370000,
    "CreationTimeTicks": 636244085156980500
}

**Comment by redknightlois** [comment]
Status of this, I believe it is fixed... Am I right?
