### ISSUE TITLE
PhpStorm freezes when project wasn't tracked previously. 

### ISSUE THREAD

**Issue by redknightlois** [Codealike/Codealike-Jetbrains#58]
Report from user: 

> Hello all. I think I have found a bug of Codealike plugin for PhpStorm (version 2017.3) in Mac High Sierra. When I try to open a project that wasn't tracked previously by Codealike, it freezes PhpStorm and it doesn't open the project. I think it could be related with the plugin because I disabled it and restarted PhpStorm and then it could open perfectly any project.

**Comment by redknightlois** [comment]
Fixed by #59.
Will be deployed in the next hour.

**Comment by Potherca** [comment]
Awesome! If anything still gives me problems after the update I'll report back here.
